LIB = ar rcs

NAME = libft.a

MY_SOURCES = ft_isalpha.c \
			 			ft_isdigit.c  \
						ft_isalnum.c \
						ft_isascii.c \
						ft_isprint.c \
						ft_toupper.c \
						ft_tolower.c \
						ft_strlen.c \
						ft_atoi.c \
						ft_memcpy.c \
						ft_memmove.c \
						ft_memset.c \
						ft_memcmp.c \
						ft_strchr.c \
						ft_bzero.c \
						ft_strlcpy.c \
						ft_calloc.c \
						ft_strjoin.c \
						ft_memchr.c \
						ft_strnstr.c \
						ft_strlcat.c \
						ft_strdup.c \
						ft_strrchr.c \
						ft_strncmp.c \
						ft_substr.c \
						ft_strtrim.c \
						ft_split.c \
						ft_itoa.c \
						ft_strmapi.c \
						ft_striteri.c \
						ft_putchar_fd.c \
						ft_putstr_fd.c \
						ft_putendl_fd.c \
						ft_putnbr_fd.c \
						ft_lstiter.c \
						ft_lstmap.c


MY_OBJECTS = $(MY_SOURCES:.c=.o)
BONUS_SOURCES = ft_lstnew.c \
					ft_lstadd_front.c \
					ft_lstsize.c \
					ft_lstlast.c \
					ft_lstadd_back.c \
					ft_lstdelone.c \
					ft_lstclear.c

BONUS_OBJECTS = $(BONUS_SOURCES:.c=.o)
CC = gcc
CFLAGS = -Wall -Wextra -Werror
$(NAME): $(MY_OBJECTS)
	@ar r $(NAME) $(MY_OBJECTS)
bonus: $(BONUS_OBJECTS)
	@ar r $(NAME) $(BONUS_OBJECTS)
all:    $(NAME)
clean:
		@rm -f $(MY_OBJECTS)
fclean: clean
		@rm -f $(NAME)
re: fclean all
.PHONY: all clean fclean re